name: Deploy Auth Project

on:
  workflow_run:
    workflows: ['Generate Auth Docker Image Stable']
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The Generate Docker Image Stable workflow passed'

  deploy:
    runs-on: ubuntu-latest
    needs: on-success
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install -r

      - name: Build project
        run: pnpm run build

      - name: Deploy
        run: echo "Deploying ..."
